/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinalps2;

/**
 *
 * @author Meu computador
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        Usar = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Editor = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Salvar = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Instr = new javax.swing.JScrollPane();
        InstrArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        Sobre = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        Licencas = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        Comandos = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        Historia = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SIC-XE | Ajuda");
        setResizable(false);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Carregar os arquivos de entrada com o botão com ícone de \"pasta\".\n2. Use o botão com ícone de \"seta\" para rodar.\n3. Botão com ícone de \"borracha\" para limpar as informações.");
        Usar.setViewportView(jTextArea2);

        jTabbedPane4.addTab("Funcionamento", Usar);

        jTextPane1.setEditable(false);
        Editor.setViewportView(jTextPane1);

        jTabbedPane4.addTab("Editor", Editor);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        Salvar.setViewportView(jTextArea3);

        jTabbedPane4.addTab("Extras", Salvar);

        jTabbedPane1.addTab("Início", jTabbedPane4);

        InstrArea.setEditable(false);
        InstrArea.setColumns(20);
        InstrArea.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        InstrArea.setRows(5);
        InstrArea.setText("MNEMÔNICO\tOPCODE\tWORDS\tOPERANDOS\tAÇÃO\t\tENDEREÇAM.\nADD\t02\t2\t1\tACC<ACC+opd1\tD/In/Im\nBR\t00\t2\t1\tPC<opd1\t\tD/In\nBRNEG\t05\t2\t1\tPC<opd1, se ACC<0\tD/In\nBRPOS\t01\t2\t1\tPC<opd1, se ACC>0\tD/In\nBRZERO\t04\t2\t1\tPC<opd1, se ACC=0\tD/In\nCALL\t15\t2\t1\t[SP]<PC; PC< opd1\tD/In\n\t\t\t\t{desvio para sub rotina opd1}\nCOPY\t13\t3\t2\topd1<opd2\t\topd1: D/In\n\t\t\t\topd2: D/In/Im\nDIVIDE\t10\t2\t1\tACC<ACC/opd1\tD/In/Im\nLOAD\t03\t2\t1\tACC<opd1\t\tD/In/Im\nMULT\t14\t2\t1\tACC<ACC*opd1\tD/In/Im\nREAD\t12\t2\t1\topd1<input stream\tD/In\nRET\t16\t1\t0\tPC< [SP]\t\t-\n\t\t\t\t{retorno de sub-rotina}\nSTOP\t11\t1\t0\t{término (fim) de execução}\nSTORE\t07\t2\t1\topd1<ACC\t\tD/In\nSUB\t06\t2\t1\tACC<ACC - opd1\tD/In/Im\nWRITE\t08\t2\t1\tOutput stream<opd1\tD/In/Im");
        Instr.setViewportView(InstrArea);

        jTabbedPane2.addTab("Instruções", Instr);

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setText("\tENTRADA\n\t/\nProcessador de Macros\n\t\\\n\tIntegrador Macro-Montador\n\t\\\n\tMontador\n\t/\nLigador de Módulos\n/\t\\\nLigador\tLigador-Relocador\n\\\t/\n     Carregador\n               |\nMáquina Virtual");
        jScrollPane4.setViewportView(jTextArea8);

        jTabbedPane2.addTab("Diagrama", jScrollPane4);

        jTabbedPane1.addTab("SIC-XE - Instruções", jTabbedPane2);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("O projeto tinha como objetivo construir um simulador completo de uma máquina virtual, construindo em cima do que foi feito no trabalho 1.\n\nComponentes:\nMacro: classe auxiliar para o processamento de macros\nMemoria: classe auxiliar para a manipulação de memória\nInstrucoes: classe auxiliar, contém definição de instruções\nLabel: classe auxiliar, conta quantas vezes a label aparece\nLigador: classe auxiliar, lê todos os arquivos de entrada e os salva como variáveis, também combina tabelas de simbolos\nSave: classe auxiliar para realizar o output através da interface\nTabelaDeUso: classe auxiliar para manipulação de tabela\nTabelaDefinicoes: classe auxiliar para manipulação de tabela\nTabelaSimbolosGlobais: classe auxiliar para manipulação de tabela\nProcessadorMacros: primeiro objeto a ser chamado, define macros baseado no arquivo de entrada\nCarregador: executa instruções e manipula memória\nMontador: Utiliza das tabelas e das macros processadas para gerar um arquivo objeto, onde existem somente binários\nPrincipal: o objeto que usa todos os outros para executar o programa inteiro\nJFrame: definição da interface");
        Sobre.setViewportView(jTextArea4);

        jTabbedPane3.addTab("Descrição", Sobre);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("- Gabriel Schubert Marten\n- Luísa Borges Lima\n- Rafael Nunes Siqueira\n- Ricardo Ferreira Padilha");
        Licencas.setViewportView(jTextArea5);

        jTabbedPane3.addTab("Equipe", Licencas);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("- Entrada (arquivo.txt)\n- Processador de Macros\n- Integrador Macro-montador\n- Montador\n- Ligador de Módulos\n- Ligador\n- Ligador-relocador\n- Carregador\n- Máquina virtual");
        Comandos.setViewportView(jTextArea6);

        jTabbedPane3.addTab("Componentes", Comandos);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("SIC-XE significa \"Simplified Instructional Computer Extra Equipment ou Extra Expensive\".\n\nÉ uma versão avançada do SIC, estando tão relacionados que possuem compatibilidade ascendente.\n\nA arquitetura de uma máquina SIC-XE consiste de:\n1. Memória: 3 bytes consecutivos que formam uma \"palavra\".\n2. Registrador: 9 registradores.\n3. Formatos: Inteiros como binários, caracteres são representados usando ASCII, ponto flutuante de 48 bits.\n4. Instruções: Formato Direto (D), Indireto (In) e Imediato (Im).\n\n");
        Historia.setViewportView(jTextArea7);

        jTabbedPane3.addTab("Sobre", Historia);

        jTabbedPane1.addTab("SIC-XE - Info", jTabbedPane3);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(">Favor desconsiderar os bugs, só estamos tentando passar na matéria...");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bugs", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Comandos;
    private javax.swing.JScrollPane Editor;
    private javax.swing.JScrollPane Historia;
    private javax.swing.JScrollPane Instr;
    private javax.swing.JTextArea InstrArea;
    private javax.swing.JScrollPane Licencas;
    private javax.swing.JScrollPane Salvar;
    private javax.swing.JScrollPane Sobre;
    private javax.swing.JScrollPane Usar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
