/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabfinalps2;

/**
 *
 * @author Meu computador
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        Usar = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Editor = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Salvar = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        Instr = new javax.swing.JScrollPane();
        InstrArea = new javax.swing.JTextArea();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        Sobre = new javax.swing.JScrollPane();
        Licencas = new javax.swing.JScrollPane();
        Comandos = new javax.swing.JScrollPane();
        Historia = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SIC-XE | Ajuda");
        setResizable(false);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        Usar.setViewportView(jTextArea2);

        jTabbedPane4.addTab("Como Usar", Usar);

        jTextPane1.setEditable(false);
        Editor.setViewportView(jTextPane1);

        jTabbedPane4.addTab("Editor", Editor);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        Salvar.setViewportView(jTextArea3);

        jTabbedPane4.addTab("Salvar", Salvar);

        jTabbedPane1.addTab(" Primeiros Passos ", jTabbedPane4);

        jTabbedPane2.addTab("tab1", jScrollPane4);

        InstrArea.setEditable(false);
        InstrArea.setColumns(20);
        InstrArea.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        InstrArea.setRows(5);
        InstrArea.setText("MNEMÔNICO\tOPCODE\tWORDS\tOPERANDOS\tAÇÃO\t\tENDEREÇAM.\nADD\t02\t2\t1\tACC<ACC+opd1\tD/In/Im\nBR\t00\t2\t1\tPC<opd1\t\tD/In\nBRNEG\t05\t2\t1\tPC<opd1, se ACC<0\tD/In\nBRPOS\t01\t2\t1\tPC<opd1, se ACC>0\tD/In\nBRZERO\t04\t2\t1\tPC<opd1, se ACC=0\tD/In\nCALL\t15\t2\t1\t[SP]<PC; PC< opd1\tD/In\n\t\t\t\t{desvio para sub rotina opd1}\nCOPY\t13\t3\t2\topd1<opd2\t\topd1: D/In\n\t\t\t\topd2: D/In/Im\nDIVIDE\t10\t2\t1\tACC<ACC/opd1\tD/In/Im\nLOAD\t03\t2\t1\tACC<opd1\t\tD/In/Im\nMULT\t14\t2\t1\tACC<ACC*opd1\tD/In/Im\nREAD\t12\t2\t1\topd1<input stream\tD/In\nRET\t16\t1\t0\tPC< [SP]\t\t-\n\t\t\t\t{retorno de sub-rotina}\nSTOP\t11\t1\t0\t{término (fim) de execução}\nSTORE\t07\t2\t1\topd1<ACC\t\tD/In\nSUB\t06\t2\t1\tACC<ACC - opd1\tD/In/Im\nWRITE\t08\t2\t1\tOutput stream<opd1\tD/In/Im");
        Instr.setViewportView(InstrArea);

        jTabbedPane2.addTab("Instruções", Instr);

        jTabbedPane1.addTab("SIC-XE - Instruções", jTabbedPane2);

        jTabbedPane3.addTab("Sobre", Sobre);
        jTabbedPane3.addTab("Licenças", Licencas);
        jTabbedPane3.addTab("Comandos", Comandos);
        jTabbedPane3.addTab("Historia", Historia);

        jTabbedPane1.addTab("SIC-XE - Info", jTabbedPane3);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(">Favor desconsiderar os bugs, só estamos tentando passar na matéria...");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bugs", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Comandos;
    private javax.swing.JScrollPane Editor;
    private javax.swing.JScrollPane Historia;
    private javax.swing.JScrollPane Instr;
    private javax.swing.JTextArea InstrArea;
    private javax.swing.JScrollPane Licencas;
    private javax.swing.JScrollPane Salvar;
    private javax.swing.JScrollPane Sobre;
    private javax.swing.JScrollPane Usar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
